character_archetypes = {
    1: {1: "Actor", 2: "Artist", 3: "Beat Cop", 4: "Bully", 5: "Cashier", 6: "CEO"},
    2: {
        1: "Clown",
        2: "Conman",
        3: "Convict / Felon",
        4: "Delivery Person",
        5: "Detective",
        6: "Drug Dealer",
    },
    3: {
        1: "Escort",
        2: "Exorcist",
        3: "Ghost Hunter",
        4: "Goth",
        5: "Hitchhiker",
        6: "Horror Writer",
    },
    4: {
        1: "Influencer",
        2: "IT / Programmer",
        3: "Janitor",
        4: "Jock",
        5: "Journalist",
        6: "Nun / Monk",
    },
    5: {
        1: "Nurse / Doctor",
        2: "Office Worker",
        3: "Paramedic",
        4: "Politician",
        5: "Preacher",
        6: "Private Eye",
    },
    6: {
        1: "Psychiatrist",
        2: "Psychic",
        3: "Socialite",
        4: "Taxi Driver",
        5: "Teacher",
        6: "Thief",
    },
}
character_secrets = {
    1: {
        1: "You’re not who you claim to be",
        2: "You lost your dream job",
        3: "You just lost your partner/spouse",
        4: "You are taking care of a child",
        5: "You recently retired / quit your crappy job",
        6: "You have a physical disability",
    },
    2: {
        1: "You were recently released from a mental facility",
        2: "You recently escaped police custody",
        3: "You are obsessed with horror movies",
        4: "You bullied someone so bad they nearly died",
        5: "You ran away from home",
        6: "You are camping out in the wilderness",
    },
    3: {
        1: "You recenly won the lottery",
        2: "You recently got out of rehab",
        3: "Someone you love recently went missing",
        4: "You got a letter from your biological parents",
        5: "You got a weird call from your ex",
        6: "You recently got out of an abusive relationship",
    },
    4: {
        1: "You recently inherited the family fortune",
        2: "You have been having visions of your own death",
        3: "When you were young you used to talk to ghosts",
        4: "You are obssessed with conspiracy theories",
        5: "You inherited a strange artifact/item",
        6: "Your blog/channel recently blew up",
    },
    5: {
        1: "You are a criminal informant",
        2: "There's something only you can fix",
        3: "Your loved one is in the hospital right now",
        4: "Your spouse is going into childbirth",
        5: "You witnessed a murder when you were young",
        6: "You just got laid with your dream person",
    },
    6: {
        1: "You're looking for a new start in a new city",
        2: "You found a weird book in the local library",
        3: "Your art has been torturing you…",
        4: "You are part of an affair",
        5: "You've been invited to the party of",
        6: "You are blackmailing someone",
    },
}
killer_masks = {
    1: {
        1: "Alien Mask",
        2: "Animal Head",
        3: "Anime Mask",
        4: "Sun Glasses",
        5: "Ski Mask",
        6: "Bandages",
    },
    2: {
        1: "Big Hat",
        2: "Biker Helmet",
        3: "Burlap Sack",
        4: "Cardboard Mask",
        5: "Carnival Mask",
        6: "Cartoon Character",
    },
    3: {
        1: "Celebrity Mask",
        2: "Clown Mask/Makeup",
        3: "Devil Mask",
        4: "Dinosaur Mask",
        5: "Doll Mask",
        6: "Eyepatch",
    },
    4: {
        1: "Gas Mask",
        2: "Guy Fawkes Mask",
        3: "Hockey Mask",
        4: "Human Flesh",
        5: "Jack O’Lantern",
        6: "Mascot Head",
    },
    5: {
        1: "Masquerade Mask",
        2: "Pantyhose",
        3: "Paper Bag",
        4: "Paper Plate",
        5: "Plague Doctor",
        6: "Skull / Skeleton",
    },
    6: {
        1: "Surgical Mask",
        2: "Theater Mask",
        3: "TV / Monitor",
        4: "VR Headset",
        5: "Veil / Wedding Veil",
        6: "Welded Metal Mask",
    },
}
killer_weapons = {
    1: {
        1: "Axe",
        2: "Baseball Bat",
        3: "Bow & Arrow",
        4: "Buzz Saw",
        5: "Cane",
        6: "Chainsaw",
    },
    2: {
        1: "Claws",
        2: "Cleaver",
        3: "Crowbar",
        4: "Folding Chair",
        5: "Garrote/Piano Wire",
        6: "Giant Scissors",
    },
    3: {
        1: "Guitar",
        2: "Hacksaw",
        3: "Hammer",
        4: "Hockey Stick",
        5: "Hook & Chain",
        6: "Ice Pick",
    },
    4: {
        1: "Katana",
        2: "Knife",
        3: "Lead Pipe",
        4: "Machete",
        5: "Musket",
        6: "Nail Gun",
    },
    5: {
        1: "Pickaxe",
        2: "Pitchfork",
        3: "Revolver",
        4: "Rope & Noose",
        5: "Scalpel",
        6: "Screwdriver",
    },
    6: {
        1: "Scythe",
        2: "Shank",
        3: "Shovel",
        4: "Spear",
        5: "Straight Razor",
        6: "Welding Torch",
    },
}
killer_traits = {
    1: {
        1: "Behaves Robotically",
        2: "Broken Shackles",
        3: "Burnt Skin",
        4: "Constantly Crying",
        5: "Constantly Laughing",
        6: "Covered in Mold",
    },
    2: {
        1: "Covered in Scars",
        2: "Covered in Tattoos",
        3: "Cultish Robes",
        4: "Clockwork Noises",
        5: "Emits Coldness",
        6: "Emits Fog",
    },
    3: {
        1: "Extra Limbs",
        2: "Extra Long Fingers",
        3: "Has Gills",
        4: "Glowing Brand",
        5: "Glowing Eyes",
        6: "Has No Shadow",
    },
    4: {
        1: "Horns",
        2: "Hot as Hell",
        3: "Long Neck",
        4: "Metallic Voice",
        5: "Music Follows Them",
        6: "Only Seen in Mirrors",
    },
    5: {
        1: "Prosthetics",
        2: "Huge Muscles",
        3: "Rotting Flesh",
        4: "Silent Footsteps",
        5: "Speaks like a Child",
        6: "Surrounded by Static",
    },
    6: {
        1: "Tall and Slender",
        2: "Tantalizing Voice",
        3: "Very Long Hair",
        4: "Walks on all Fours",
        5: "Wedding Dress",
        6: "Wide Frame",
    },
}

journal_prompts = {
    (1, 1): "First time rolling a 1: Do something.",
    (1, 2): "Second time rolling a 1: Do something else.",
    (1, 3): "Third time rolling a 1: Do another thing.",
    (1, 4): "Fourth time rolling a 1: Do something different.",
    (1, 5): "Fifth time rolling a 1: Do this action.",
    (1, 6): "Sixth time rolling a 1: Now do this different action.",
    (2, 1): "First time rolling a 2: Do something.",
    (2, 2): "Second time rolling a 2: Do something else.",
    (2, 3): "Third time rolling a 2: Do another thing.",
    (2, 4): "Fourth time rolling a 2: Do something different.",
    (2, 5): "Fifth time rolling a 2: Do this action.",
    (2, 6): "Sixth time rolling a 2: Now do this different action.",
    (3, 1): "First time rolling a 3: Do something.",
    (3, 2): "Second time rolling a 3: Do something else.",
    (3, 3): "Third time rolling a 3: Do another thing.",
    (3, 4): "Fourth time rolling a 3: Do something different.",
    (3, 5): "Fifth time rolling a 3: Do this action.",
    (3, 6): "Sixth time rolling a 3: Now do this different action.",
    (4, 1): "First time rolling a 4: Do something.",
    (4, 2): "Second time rolling a 4: Do something else.",
    (4, 3): "Third time rolling a 4: Do another thing.",
    (4, 4): "Fourth time rolling a 4: Do something different.",
    (4, 5): "Fifth time rolling a 4: Do this action.",
    (4, 6): "Sixth time rolling a 4: Now do this different action.",
    (5, 1): "First time rolling a 5: Do something.",
    (5, 2): "Second time rolling a 5: Do something else.",
    (5, 3): "Third time rolling a 5: Do another thing.",
    (5, 4): "Fourth time rolling a 5: Do something different.",
    (5, 5): "Fifth time rolling a 5: Do this action.",
    (5, 6): "Sixth time rolling a 5: Now do this different action.",
    (6, 1): "First time rolling a 6: Do something.",
    (6, 2): "Second time rolling a 6: Do something else.",
    (6, 3): "Third time rolling a 6: Do another thing.",
    (6, 4): "Fourth time rolling a 6: Do something different.",
    (6, 5): "Fifth time rolling a 6: Do this action.",
    (6, 6): "Sixth time rolling a 6: Now do this different action.",
}